"""adicionando Category slug

Revision ID: 5c9c2ff2522e
Revises: 4f538b02c5fc
Create Date: 2022-11-08 17:44:48.604949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9c2ff2522e'
down_revision = '4f538b02c5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_category_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###
    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
