"""corrigi relação software com fonte

Revision ID: 7dbc65952339
Revises: 5c9c2ff2522e
Create Date: 2024-08-06 13:43:21.150431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbc65952339'
down_revision = '5c9c2ff2522e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index('ix_category_slug')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=200), nullable=True))
        batch_op.create_index('ix_category_slug', ['slug'], unique=False)

    # ### end Alembic commands ###
